- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Start and Enable Apache
  service:
    name: httpd
    state: started
    enabled: yes

- name: Start firewalld
  service: 
    name: firewalld 
    state: started 
    enabled: yes

- name: Set Firewall rule
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
    immediate: yes

- name: Apply Jinja Template
  template:
    src: home_cfg.conf.j2
    dest: /etc/httpd/conf.d/home_cfg.conf
  notify:
    - Restart Apache

- name: Copy Webpage PHP files
  template:
    src: index.php
    dest: /var/www/html/index.php
  notify:
    - Restart Apache